service: rendertron
runtime: nodejs12
instance_class: F4_1G
automatic_scaling:
  min_instances: 0

handlers:
  - url: /
    login: admin

env_variables:
  DISABLE_LEGACY_METADATA_SERVER_ENDPOINTS: "true"
